<Project>
  <PropertyGroup>
    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild Condition="'$(Configuration)' == 'Release'">true</ContinuousIntegrationBuild>
    <PathMap>$([System.String]::Copy('$(MSBuildThisFileDirectory)').TrimEnd('\'))=/_/</PathMap>
  </PropertyGroup>
</Project>
